import { NextResponse } from 'next/server'
import { resolveAccess } from '@/lib/auth/session'
import { enqueueIngest } from '@/lib/arsenal/store'
import { publicUrl } from '@/lib/arsenal/storage'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

// Browser-side file upload counterpart to /api/arsenal/ingest-url.
// Flow:
//   1. Admin UI POSTs to /api/arsenal/upload-url with a queue_id hint
//      → gets back signed PUT URLs for video + (optional) thumbnail.
//   2. Browser PUTs the bytes straight to Supabase Storage.
//   3. Browser POSTs here with the resulting videoPath (+ optional
//      thumbnailPath + question/brief), which creates a queue row
//      with source_platform='browser_upload' and source_url set to
//      the public URL of the uploaded mp4. From that point on the
//      pipeline is identical to a URL-based ingest — the local skill
//      pulls the row and extracts hooks/structure/proposal.

interface Body {
  clinicId?: string
  // Bucket key in arsenal-videos, e.g. "<clinicId>/<queueIdHint>_xx.mp4".
  // Generated by /api/arsenal/upload-url so the path is stable across
  // browser PUT and our enqueue.
  videoPath?: string
  thumbnailPath?: string
  // The "question / brief" — same role as the link+question TG flow.
  // When non-trivial, the queue row is tagged template_for_clinic.
  userContext?: string
  // Optional short display label the admin typed in the form (filename
  // by default). Used only for the requested_by_name field so the
  // pending-queue UI shows something meaningful next to the row.
  displayLabel?: string
}

export async function POST(req: Request) {
  const access = await resolveAccess()
  if (!access || access.role !== 'admin') {
    return NextResponse.json({ error: 'admin access required' }, { status: 403 })
  }
  let body: Body
  try {
    body = (await req.json()) as Body
  } catch {
    return NextResponse.json({ error: 'invalid body' }, { status: 400 })
  }
  const clinicId = body.clinicId?.trim()
  const videoPath = body.videoPath?.trim()
  if (!clinicId || !videoPath) {
    return NextResponse.json(
      { error: 'clinicId and videoPath required' },
      { status: 400 }
    )
  }
  // Derive the public URL — the skill will fetch from there. We store
  // this in source_url so the queue row looks the same as a URL-based
  // ingest from the skill's perspective. (skill checks
  // source_platform to decide which loader to use.)
  const sourceUrl = publicUrl(videoPath)
  if (!sourceUrl) {
    return NextResponse.json(
      { error: 'failed to derive public URL for uploaded file' },
      { status: 500 }
    )
  }
  const userContext = body.userContext?.trim()
  const wantsTemplate = !!userContext && userContext.length >= 8
  const requestedByName = body.displayLabel?.trim() || 'admin:web'
  try {
    const { row, reused, upgraded } = await enqueueIngest({
      clinicId,
      sourceUrl,
      platform: 'browser_upload',
      requestedByChatId: null,
      requestedByName,
      intent: wantsTemplate ? 'template_for_clinic' : 'ingest_only',
      userContext: wantsTemplate ? userContext : null,
    })
    return NextResponse.json({
      ok: true,
      queue: row,
      reused,
      upgraded,
      // Echo back for client-side hydration of the optimistic queue
      // list (so the new row appears before the next revalidation).
      video_storage_path: videoPath,
      thumbnail_storage_path: body.thumbnailPath ?? null,
    })
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'unknown'
    return NextResponse.json({ ok: false, error: msg }, { status: 500 })
  }
}
