-- ============================================================
-- Content Machine — Migration 003
-- Adds clinic_access_tokens for cookie-based doctor login.
-- A token is generated by an admin/owner and shared once with
-- the doctor; on first visit the server sets a long-lived cookie
-- and the bare token URL becomes the bootstrap mechanism only.
-- Run in Supabase SQL Editor after 002.
-- ============================================================

create table if not exists public.clinic_access_tokens (
  token text primary key,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  role text not null default 'doctor' check (role in ('doctor', 'editor')),
  label text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists idx_clinic_access_tokens_clinic
  on public.clinic_access_tokens(clinic_id);

create index if not exists idx_clinic_access_tokens_active
  on public.clinic_access_tokens(clinic_id)
  where revoked_at is null;

-- RLS: app code uses service-role key, so RLS is bypassed.
-- Enabling it here as a defence-in-depth: any future anon client
-- read attempt is denied unless we add an explicit policy.
alter table public.clinic_access_tokens enable row level security;
