-- ============================================================
-- Content Machine — Migration 013
-- Adds caption fields to scripts. Each post now ships with two
-- captions alongside the script: short (Reels/TikTok flavour, 1-2
-- sentences + 3-5 hashtags) and long (Instagram carousel flavour,
-- 3-5 sentences + CTA + hashtags). Both share the script's topic
-- but use a different format. Generated by lib/agents/captioner.ts
-- (Haiku 4.5) right after the critic picks a winner.
-- Run in Supabase SQL Editor after 012.
-- ============================================================

alter table public.scripts
  add column if not exists short_caption text,
  add column if not exists long_caption text;
