-- ============================================================
-- Content Machine — Migration 014
-- Script arsenal: ingest reference videos (IG/YT/TikTok URLs the
-- doctor drops in Telegram) and extract reusable style/hook/structure
-- patterns the Writer can borrow from. Each ingested video becomes a
-- distinct *style* row — doctor can flip is_active off if the style
-- stops working, so it stops bleeding into Writer's brief.
--
-- Two tables:
--   video_ingest_queue — TG webhook drops URL here, status=pending.
--     A local Claude Code skill (~/.claude/skills/script-arsenal-ingest)
--     polls, runs yt-dlp + audio analysis, POSTs results back, then
--     marks status=completed.
--   script_arsenal — confirmed style entries the Writer reads via brief.
--     One row per style. is_active=true means it's in active rotation.
--
-- Run in Supabase SQL Editor after 013.
-- ============================================================

create table if not exists public.video_ingest_queue (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  source_url text not null,
  source_platform text not null default 'unknown'
    check (source_platform in ('instagram','youtube','tiktok','twitter','unknown')),
  -- Where to ping back when ingestion finishes. String because TG
  -- chat ids exceed int range for groups and we treat them as opaque.
  requested_by_chat_id text,
  requested_by_name text,
  status text not null default 'pending'
    check (status in ('pending','processing','awaiting_confirm','completed','failed','skipped')),
  -- arsenal_id is set when the skill posts a draft to /api/arsenal/draft.
  -- It points at the script_arsenal row that's waiting on doctor confirm.
  arsenal_id uuid,
  error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists idx_video_ingest_queue_clinic
  on public.video_ingest_queue(clinic_id, status, created_at desc);

-- Avoid re-ingesting the exact same URL for the same clinic.
create unique index if not exists ux_video_ingest_queue_url
  on public.video_ingest_queue(clinic_id, source_url);

alter table public.video_ingest_queue enable row level security;

drop policy if exists "clinic_isolation_video_ingest_queue" on public.video_ingest_queue;
create policy "clinic_isolation_video_ingest_queue" on public.video_ingest_queue
  for all using (clinic_id = nullif(current_setting('app.clinic_id', true), '')::uuid);

-- ------------------------------------------------------------

create table if not exists public.script_arsenal (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  queue_id uuid references public.video_ingest_queue(id) on delete set null,
  source_url text,
  source_platform text,
  -- Operator-facing label. Auto-generated by the extractor as a short
  -- kebab-case slug (e.g. "punchy-question-hook"). Doctor can rename it.
  style_label text not null,
  -- One-liner explaining what's distinctive about this style. Surfaces
  -- in the TG "/arsenal list" listing and in the Writer's brief.
  style_description text,
  -- Short human-readable title for the source video.
  title text,
  -- Full transcript (kept so we can re-extract later with a better prompt).
  full_transcript text,
  -- Structured extraction. Shape (set by extractor):
  --   hooks: [{ text: string, position_sec?: number, why_it_works?: string }]
  --   structure: { beats: [{ name: string, text: string, sec?: number }] }
  --   pains: string[]   (patient-voice problems mentioned)
  hooks jsonb not null default '[]'::jsonb,
  structure jsonb not null default '{}'::jsonb,
  pains jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}',
  -- is_active=false hides it from Writer's brief but keeps the row
  -- (so doctor can flip it back on later without re-ingesting).
  is_active boolean not null default false,
  -- Set when doctor confirms "save to arsenal" in TG. Until then the
  -- row exists with is_active=false (status awaiting_confirm in queue).
  confirmed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_script_arsenal_clinic_active
  on public.script_arsenal(clinic_id, is_active, created_at desc);

create index if not exists idx_script_arsenal_label
  on public.script_arsenal(clinic_id, style_label);

alter table public.script_arsenal enable row level security;

drop policy if exists "clinic_isolation_script_arsenal" on public.script_arsenal;
create policy "clinic_isolation_script_arsenal" on public.script_arsenal
  for all using (clinic_id = nullif(current_setting('app.clinic_id', true), '')::uuid);
