-- ============================================================
-- Content Machine — Migration 016
-- Link + question pattern: doctor drops a TG/IG/YT URL alongside
-- a free-form question like "опиши его структуру и как это может
-- быть для наших видео темплейтов". The webhook captures the
-- non-URL text as user_context and tags the queue row with
-- intent='template_for_clinic'. The local Claude Code skill then
-- not only extracts hooks/structure/pains as usual, but also
-- writes a clinic-tailored template proposal — a concrete
-- scaffold filled with this clinic's niche / services / tone, not
-- just an abstract beat list. Doctor confirms in TG → the
-- proposal mirrors into script_templates and shows up in the
-- /arsenal Templates tab in the webapp.
--
-- Backwards compatible: existing rows keep intent='ingest_only'
-- and the skill's old path (no proposal) still works.
-- Run in Supabase SQL Editor after 015.
-- ============================================================

alter table public.video_ingest_queue
  -- 'ingest_only' = behave like before (just style extraction).
  -- 'template_for_clinic' = also synthesise a clinic-tailored
  -- template scaffold the doctor can save into script_templates.
  add column if not exists intent text not null default 'ingest_only'
    check (intent in ('ingest_only', 'template_for_clinic')),
  -- Free-form text the doctor sent alongside the URL ("опиши
  -- структуру и как это может быть для наших темплейтов"). The
  -- skill reads it as a question/spec when generating the
  -- clinic-tailored proposal. Nullable for legacy/plain ingest.
  add column if not exists user_context text;

alter table public.script_arsenal
  -- Clinic-tailored template proposal generated by the skill
  -- when the queue row's intent='template_for_clinic'. Plain
  -- text (same shape as script_templates.scaffold) so it can be
  -- mirrored straight into script_templates on confirm.
  add column if not exists clinic_template_proposal text,
  -- Short explanation of HOW this proposal maps the source
  -- video's pattern onto this clinic specifically (one-liner
  -- shown above the proposal in the UI + TG ping).
  add column if not exists clinic_template_note text;
